add shopping cart model
oleksii-sukhenko/spring-boot-intro pull request #11
Opened 2024-09-28 16:10 UTC by oleksii-sukhenko

2024-09-29 17:41 UTC, Elena-Bruyako requested changes
see comments

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +@RequestMapping(value = "/cart")
```suggestion
@RequestMapping("/cart")
```

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +        return shoppingCartService.getAllInfo(authentication);
it's better to provide user or userId instead of authentication

Fix other endpoints

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +            @RequestBody CartItemRequestDto requestDto,
```suggestion
            @RequestBody @Valid CartItemRequestDto requestDto,
```

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +    public CartItemDto addBookToShoppingCart(
```suggestion
    public ShoppingCartDto addBookToShoppingCart(
```

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +    public CartItemDto changeNumberOfBooks(
```suggestion
    public ShoppingCartDto changeNumberOfBooks(
```

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/cartitem/CartItemRequestDto.java
> +    @NotNull
```suggestion
    @NotNull
    @Positive
```

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "shopping_cart_id", nullable = false)
```

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "book_id", nullable = false)
```

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/ShoppingCart.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
```

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/cartitem/CartItemService.java
> +public interface CartItemService {
remove service, all operations should be in ShopCartService

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/user/UserService.java
> +    User findById(Long id);
remove

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/user/impl/UserServiceImpl.java
> +    public User findById(Long id) {
remove

2024-09-29 17:41 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/09-create-cart-items-table.yaml
add empty line

2024-10-03 12:22 UTC, Elena-Bruyako requested changes
see comments

2024-10-03 12:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
```

2024-10-03 12:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(id).orElseThrow(
```suggestion
        ShoppingCart cart = shoppingCartRepository.findByUserId(userId);
        CartItem cartItem = cartItemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())
```

2024-10-03 12:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +    @Override
suggest to add createShoppingCart(User user) method and call it in UserService register method
It's better to create shop cart for user during registration

2024-10-07 08:32 UTC, ahoienko approved these changes
Good job!

2024-10-14 16:17 UTC, merged