spring-boot-data-jpa
oleksii-sukhenko/spring-boot-intro pull request #3
Opened 2024-09-05 04:42 UTC by oleksii-sukhenko

extend jpa repository
add liquibase support
implement put and deleted functional

2024-09-05 13:00 UTC, Elena-Bruyako requested changes
see comments

2024-09-05 13:00 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Book.java
> +    @Column(nullable = false, name = "is_deleted", columnDefinition = "TINYINT")
```suggestion
    private String coverImage;
    @Column(nullable = false, columnDefinition = "TINYINT")
```

2024-09-05 13:00 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +        book.setTitle(requestDto.getTitle());
use mapstruct for setting

2024-09-06 08:47 UTC, sarakhmen approved these changes

2024-09-06 18:59 UTC, merged