GlobalExceptionHandler
oleksii-sukhenko/spring-boot-intro pull request #5
Opened 2024-09-09 15:34 UTC by oleksii-sukhenko

add CustomGlobalExceptionHandler class
add meaningful validation for existing DTO classes

2024-09-10 06:46 UTC, Elena-Bruyako requested changes
see comments

2024-09-10 06:46 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/BookController.java
> +    public BookDto createBook(@RequestBody @Valid CreateBookRequestDto bookDto) {
add `@Valid` in updateBookById endpoint

2024-09-10 06:46 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +    @NotNull
```suggestion
    @NotBlank
```

for String

2024-09-10 06:46 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +    @NotNull
```suggestion
```

You can validate Size

2024-09-10 06:46 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +    @NotNull
```suggestion
```
You can validate Size

2024-09-10 06:46 UTC, Elena-Bruyako commented on src/main/java/mate/academy/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, headers, status);
```suggestion
        return new ResponseEntity<>(body, headers, HttpStatus.BAD_REQUEST);
```

2024-09-11 08:54 UTC, okuzan approved these changes

2024-09-11 08:54 UTC, okuzan commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +    @Min(1)
You can use DecimalMin

2024-09-11 14:15 UTC, merged